/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package byfconreg;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author CHRIS PHILIP
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     * 
     */
     Statement state;
    String Glevel, Gpass;
    ResultSet set;
    Connection con;
   
    int IntStatus, IntAttend;
    public registration() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        File icon = new File("src\\byfconreg\\icon.png");
        BufferedImage img;
         try {
             img = ImageIO.read(icon);
             this.setIconImage(img);
         } catch (IOException ex) {
             Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
         }
        
       // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        jTextField1.setCaretPosition(0);
        jTextField2.setCaretPosition(0);
        jTextField3.setCaretPosition(0);
        jTextField4.setCaretPosition(0);
        int attendance = 0;
         int status = 0;
       
          try {
            Class.forName("org.sqlite.JDBC");
             con = DriverManager.getConnection("jdbc:sqlite:attendance.db");
            state = con.createStatement();
           
            
     set = state.executeQuery("select * from registered" );
     // JOptionPane.showMessageDialog(null, "CONNECTED TO DATABASE");
             
            
            
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            //Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THE BURNING YOUTH FELLOWSHIP NATIONAL CONVENTION 2017");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 11, -1, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("( HEAVENLY BOUND! EARTHLY SUCCESSFUL)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byfconreg/FB_IMG_1500928175900-1-1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("select a tab to work on");
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("FULL NAME");
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField1MouseReleased(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 513, 45));

        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("BRANCH NAME");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 513, 45));

        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("PHONE NUMBER");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 513, 45));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("REGISTRATION FORM");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, -1, 47));

        jLabel7.setFont(new java.awt.Font("Playbill", 1, 110)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("WHAT GENERATION IS THIS");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 1070, 180));

        jLabel8.setFont(new java.awt.Font("Playbill", 1, 110)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("WHAT GENERATION IS THIS");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 1070, 180));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Sign up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, 40));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, -1, 40));

        jTabbedPane1.addTab("REGISTER", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("WHAT GENERATION IS THIS");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 350, 110));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("please enetr the phone number");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 32, -1, 47));

        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Enter Phone Number Here");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 90, 520, 45));

        jCheckBox1.setBackground(new java.awt.Color(255, 153, 153));
        jCheckBox1.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("ADMITED");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, -1, 40));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("SIGN IN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 393, 110, 40));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 620, 270));

        jTabbedPane1.addTab("CONFIRM", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        // TODO add your handling code here:
        //this handles the ghost text apearance and disaperance
        
             String ID =  jTextField1.getText();
      if(ID.equals("FULL NAME")){
          jTextField1.setText("");
           jTextField1.setForeground(Color.black);
      }else if (jTextField1.getText().length()<1) {
           jTextField1.setCaretPosition(0);
           jTextField1.setForeground(Color.gray);
          jTextField1.setText("FULL NAME");
          
      }
    }//GEN-LAST:event_jTextField1MousePressed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        /* TODO add your handling code here:
           String ID =  jTextField1.getText();
      if(ID.equals("FULL NAME")){
          jTextField1.setText("");
           jTextField1.setForeground(Color.black);
      }else if (jTextField1.getText().length()<1) {
           jTextField1.setCaretPosition(0);
           jTextField1.setForeground(Color.gray);
          jTextField1.setText("FULL NAME");
          
      }*/
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseReleased
        // TODO add your handling code here:
                   String ID =  jTextField1.getText();
      if(ID.equals("FULL NAME")){
          jTextField1.setText("");
           jTextField1.setForeground(Color.black);
      }else if (jTextField1.getText().length()<1) {
           jTextField1.setCaretPosition(0);
           jTextField1.setForeground(Color.gray);
          jTextField1.setText("FULL NAME");
          
      }
    }//GEN-LAST:event_jTextField1MouseReleased

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
                    String ID =  jTextField1.getText();
      if(ID.equals("FULL NAME")){
          jTextField1.setText("");
           jTextField1.setForeground(Color.black);
      }else if (jTextField1.getText().length()<1) {
           jTextField1.setCaretPosition(0);
           jTextField1.setForeground(Color.gray);
          jTextField1.setText("FULL NAME");
          
      }   
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
                     String ID =  jTextField1.getText();
      if(ID.equals("FULL NAME")){
          jTextField1.setText("");
           jTextField1.setForeground(Color.black);
      }else if (jTextField1.getText().length()<1) {
           jTextField1.setCaretPosition(0);
           jTextField1.setForeground(Color.gray);
          jTextField1.setText("FULL NAME");
          
      } 
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
                     String ID =  jTextField2.getText();
      if(ID.equals("BRANCH NAME")){
          jTextField2.setText("");
           jTextField2.setForeground(Color.black);
      }else if (jTextField2.getText().length()<1) {
           jTextField2.setCaretPosition(0);
           jTextField2.setForeground(Color.gray);
          jTextField2.setText("BRANCH NAME");
          
      }    
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
                     String ID =  jTextField2.getText();
      if(ID.equals("BRANCH NAME")){
          jTextField2.setText("");
           jTextField2.setForeground(Color.black);
      }else if (jTextField2.getText().length()<1) {
           jTextField2.setCaretPosition(0);
           jTextField2.setForeground(Color.gray);
          jTextField2.setText("BRANCH NAME");
          
      }    
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
                     String ID =  jTextField3.getText();
      if(ID.equals("PHONE NUMBER")){
          jTextField3.setText("");
           jTextField3.setForeground(Color.black);
      }else if (jTextField3.getText().length()<1) {
           jTextField3.setCaretPosition(0);
           jTextField3.setForeground(Color.gray);
          jTextField3.setText("PHONE NUMBER");
          
      }    
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
                        String ID =  jTextField4.getText();
      if(ID.equals("Enter Phone Number Here")){
          jTextField4.setText("");
           jTextField4.setForeground(Color.black);
      }else if (jTextField4.getText().length()<1) {
           jTextField4.setCaretPosition(0);
           jTextField4.setForeground(Color.gray);
          jTextField4.setText("Enter Phone Number Here");
          
      }
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
                      String ID =  jTextField4.getText();
      if(ID.equals("Enter Phone Number Here")){
          jTextField4.setText("");
           jTextField4.setForeground(Color.black);
      }else if (jTextField4.getText().length()<1) {
           jTextField4.setCaretPosition(0);
           jTextField4.setForeground(Color.gray);
          jTextField4.setText("Enter Phone Number Here");
          
      }       
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
                        String ID =  jTextField3.getText();
      if(ID.equals("PHONE NUMBER")){
          jTextField3.setText("");
           jTextField3.setForeground(Color.black);
      }else if (jTextField3.getText().length()<1) {
           jTextField3.setCaretPosition(0);
           jTextField3.setForeground(Color.gray);
          jTextField3.setText("PHONE NUMBER");
          
      }          
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     jTextField1.setForeground(Color.gray);
     jTextField1.setText("FULL NAME");
     jTextField2.setForeground(Color.gray);
     jTextField2.setText("BRANCH NAME");
     jTextField3.setForeground(Color.gray);
     jTextField3.setText("PHONE NUMBER");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    String Fname= jTextField1.getText();
    String Bname = jTextField2.getText();
    String PhoneNO =jTextField3.getText();
    int attendance = 0;
         int status = 0;
    if(Fname.equalsIgnoreCase("FULL NAME") || Bname.equalsIgnoreCase("BRANCH NAME") || PhoneNO.equalsIgnoreCase("PHONE NUMBER")){
        JOptionPane.showMessageDialog(this, "Please fill all available Fields\n click ok to continue");
    }else{
        try {
          //JOptionPane.showMessageDialog(this, "ready to insert");   
            String query = "insert into registered values (?,?,?,?,?);";
            PreparedStatement pst =   con.prepareStatement(query);
             //JOptionPane.showMessageDialog(this, "insertered");
            //state.executeUpdate("insert into registered value (?,?,?,?,?);");
            pst.setString(1, Fname);
            pst.setString(2, Bname);
            pst.setString(3, PhoneNO);
            pst.setInt(4, status);
            pst.setInt(5, attendance);
        pst.executeUpdate();
            JOptionPane.showConfirmDialog(this, "do you want to save?");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
            
            //Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      /*  if (!Bname.equals(jLabel5.getText())){
           jLabel10.setText(Bname);
        }else if(Bname.equals(jLabel5.getText())){
            if(!Bname.equals(jLabel10.getText())){
              jLabel11.setText(Bname);  
            }else if(Bname.equals(jLabel10.getText())){
                if(!Bname.equals(jLabel11.getText())){
                    jLabel12.setText(Bname);
                }else if (Bname.equals(jLabel11.getText())){
                    if(!Bname.equals(jLabel12.getText())){
                        jLabel13.setText(Bname);
                    }else if(Bname.equals(jLabel12.getText())){
                        if(!Bname.equals(jLabel13.getText())){
                            jLabel13.setText(Bname);
                        }else{
                            
                        }
                    }
                }
            }
        }*/
           jTextField1.setForeground(Color.gray);
     jTextField1.setText("FULL NAME");
     jTextField1.setFocusCycleRoot(true);
     jTextField2.setForeground(Color.gray);
     jTextField2.setText("BRANCH NAME");
     jTextField3.setForeground(Color.gray);
     jTextField3.setText("PHONE NUMBER");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        try{
        long lPhoneNo = Long.parseLong(jTextField3.getText());
        }catch(NumberFormatException ex){
         JOptionPane.showMessageDialog(null, "Text Not Allow","ERROR", JOptionPane.ERROR_MESSAGE);
          jTextField3.setForeground(Color.gray);
     jTextField3.setText("PHONE NUMBER");
        } 
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // try{
            boolean Cstatus = jCheckBox1.isSelected();
            if(Cstatus==true){
                try {
                    String getPhone = jTextField4.getText();
                    //JOptionPane.showMessageDialog(this, getPhone);
                    int aa = 1;
           set =         state.executeQuery("SELECT * FROM registered WHERE phone = '"+getPhone+"'  ");
          // JOptionPane.showMessageDialog(this, "Admited good"  );
                    while(set.next()){
                       // JOptionPane.showMessageDialog(this, "Admiteuuuuuud");
                        String Attend = set.getString("status");
                        String Status = set.getString("attendance");
                        IntAttend = Integer.parseInt(Attend);
                        IntStatus =Integer.parseInt(Status);
                        IntAttend = IntAttend + 1;
                        IntStatus = 1;
                        
                    //JOptionPane.showMessageDialog(this, "Admitting");
                    }
                        state = con.createStatement();
                        state.executeUpdate("UPDATE registered SET status ='"+IntStatus+"', attendance = '"+IntAttend+"' WHERE phone = '"+getPhone+"' ");
                   
                    JOptionPane.showMessageDialog(this, "Admited");
                //} catch (SQLException ex) {
                    //ex.printStackTrace();
                    //Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                //}
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    //Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else {
                try {
                    state = con.createStatement();
                    String getPhone = jTextField4.getText();
                    IntStatus = 0;
                    
                    state.executeUpdate("UPDATE registered SET status ='"+IntStatus+"' WHERE phone = '"+getPhone+"' ");
                    JOptionPane.showMessageDialog(this, "Not Admited\nMake sure you checked the checkbox");
                } catch (SQLException ex) {
                    Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
           // ResultSet set = state.executeUpdate(Glevel)
                //}catch(SQLException EM){
                    
                //}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
           try{
        long lPhoneNo = Long.parseLong(jTextField4.getText());
        }catch(NumberFormatException ex){
         JOptionPane.showMessageDialog(null, "Text Not Allowed","ERROR", JOptionPane.ERROR_MESSAGE);
          jTextField4.setForeground(Color.gray);
     jTextField4.setText("Enter Phone Number Here");
    
        }
         try{
            String phoneNoGet = jTextField4.getText();
       ResultSet set = state.executeQuery("select * from registered where phone = '"+phoneNoGet+"'");
        while (set.next()){
            String Fname = set.getString("names");
            String PhoneNo = set.getString("phone");
            String Branch = set.getString("branch");
            String Status = set.getString("status");
            String attendance = set.getString("attendance");
            int IntStatus = Integer.parseInt(Status);
            String realStatus;
            if(IntStatus == 0){
                realStatus = "OUT";
            }else{
                realStatus = "IN";
            }
        jTextPane1.setText("NAME:\t\t\t"+Fname+"\n"+"PHONE NUMBER:\t\t"+"0"+PhoneNo+"\nBRANCH:\t\t\t"+Branch+"\nSTATUS:\t\t\t"+realStatus+"\nNO OF ATTENDANCE:\t\t"+attendance); 
        //JOptionPane.showMessageDialog(this, "ok");
        
        }
        
            
            }catch(SQLException EM){
              EM.printStackTrace();
                    
                }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
